services:
  piperchat-service:
    image: piperchat
    command: ['npm', 'run', '--workspace', './services/piperchat', 'start']
    expose:
      - '3000'
    depends_on:
      db-piperchat-service:
        condition: service_healthy
      broker:
        condition: service_healthy
    networks:
      - piperchat-network
      - backend
      - frontend
    environment:
      - 'AMQP_URI=${BROKER_URI}'
      - 'MONGO_URI=mongodb://db-piperchat-service:27017/piperchat'

  db-piperchat-service:
    image: mongo
    expose:
      - '27017'
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongo --quiet $${host}/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
    networks:
      - piperchat-network

networks:
  piperchat-network:
