services:
  notifications-service:
    image: piperchat
    command: ['npm', 'run', '--workspace', './services/notifications', 'start']
    expose:
      - '3000'
    depends_on:
      db-notifications-service:
        condition: service_healthy
      broker:
        condition: service_healthy
    networks:
      - notifications-network
      - backend
      - frontend
    environment:
      - 'AMQP_URI=${BROKER_URI}'
      - 'MONGO_URI=mongodb://db-notifications-service:27017/notifications'

  db-notifications-service:
    image: mongo
    expose:
      - '27017'
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongo --quiet $${host}/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
    networks:
      - notifications-network

networks:
  notifications-network:
