services:
  # gateway:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./services/gateway/conf.d:/etc/nginx/
  #   depends_on:
  #     - messages-service
  #     - monitoring-service
  #     - notifications-service
  #     - piperchat-service
  #     - users-service
  #     - webrtc-service
  #   networks:
  #     - frontend

  gateway:
    image: traefik:v2.10
    command: |
      --api.insecure=true
      --providers.docker
      --providers.docker.network=piperchat_frontend
      --log.level=DEBUG
      --accesslog
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    depends_on:
      - frontend-service
      - messages-service
      - monitoring-service
      - notifications-service
      - piperchat-service
      - users-service
      - webrtc-service
    networks:
      - frontend

networks:
  frontend:
