services:
  gateway:
    image: traefik:v2.10
    command: |
      --api.insecure=true
      --providers.docker
      --providers.docker.network=piperchat_frontend
      --log.level=DEBUG
      --accesslog
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    labels:
      - 'traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=*'
      - 'traefik.http.middlewares.testheader.headers.accesscontrolalloworigin=*'
      - 'traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100'
      - 'traefik.http.middlewares.testheader.headers.addvaryheader=true'
    depends_on:
      - frontend-service
      - messages-service
      - monitoring-service
      - notifications-service
      - piperchat-service
      - users-service
      - multimedia-service
    networks:
      - frontend

networks:
  frontend:
