version: '1'

services:
  webrtc-service:
    image: piperchat
    command: ['npm', 'run', '--workspace', './services/piperchat', 'start']
    expose:
      - '3000'
    depends_on:
      db-webrtc-service:
        condition: service_healthy
      broker:
        condition: service_healthy
      coturn:
        condition: service_started
    networks:
      - webrtc-network
      - backend
      - frontend
    environment:
      - 'AMQP_URI=${BROKER_URI}'
      - 'MONGO_UTI=mongodb://db-webrtc-service:27017'

  db-webrtc-service:
    image: mongo
    expose:
      - '27017'
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongo --quiet $${host}/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
    networks:
      - webrtc-network

  coturn:
    image: flaviostutz/coturn
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 5349:5349
      - 5349:5349/udp
    environment:
      - TURN_USERNAME=coturn
      - TURN_PASSWORD=coturn-password

networks:
  webrtc-network:
