services:

  webrtc-service:
    build: ./services/webrtc
    expose:
      - "3000"
    depends_on:
      db-webrtc-service:
        condition: service_healthy
      broker:
        condition: service_healthy
    networks:
      - webrtc-network
      - backend
      - frontend
    environment:
      - "AMQP_URI=${BROKER_URI}"
      - "MONGO_URI=mongodb://db-webrtc-service:27017/webrtc"

  db-webrtc-service:
    image: mongo
    expose:
      - "27017"
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongo --quiet $${host}/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
    networks:
      - webrtc-network

networks:
  webrtc-network:
