
services:

  broker:
    image: rabbitmq:3-management-alpine
    hostname: ${BROKER_HOSTNAME}
    expose:
      - "${BROKER_PORT}"
    # for development only
    # ports:
    #   - "15672:15672"
    # volumes:
    #   - .docker/broker/data/:/var/lib/broker/
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]

networks:
  backend:
