include:
  - path: docker-compose.yaml

services:

  # Broker
  broker:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - .docker/rabbitmq/data/:/var/lib/rabbitmq/
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: "db-users-service"
    depends_on:
      db-users-service:
        condition: service_healthy
    networks:
      - users-network

networks:
  backend:
  frontend:
