openapi: '3.0.3'
info:
  title: Piperchat API
  version: '1.0'
  description: |
    Piperchat design API description

paths:
  /auth/login:
    post:
      parameters:
        - in: query
          name: username
          required: true
          description: Username of the user to be logged in
          schema:
            type: string
          example: user1
        - in: query
          name: password
          schema:
            type: string
          required: true
          description: Password of the user to be logged in
          example: 123456
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
