name: Check code style and lint
run-name: Check style by ${{ github.actor }}
on:
  push:
  workflow_dispatch:

jobs:
  style-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: |
          npm ci
      - name: Check code style
        run: |
          npm run check:pretty
      - name: Check lint
        run: |
          npm run lint
