services:

  monitoring-service:
    build: ./services/monitoring
    expose:
      - "3000"
    depends_on:
      db-monitoring-service:
        condition: service_healthy
      broker:
        condition: service_healthy
    networks:
      - monitoring-network
      - backend
      - frontend
    environment:
      - "AMQP_URI=${BROKER_URI}"
      - "MONGO_URI=mongodb://db-monitoring-service:27017/monitoring"

  db-monitoring-service:
    image: mongo
    expose:
      - "27017"
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongo --quiet $${host}/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
    networks:
      - monitoring-network

networks:
  monitoring-network:
