version: "1"

services:
  # Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - .docker/rabbitmq/data/:/var/lib/rabbitmq/
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10

  db-monitoring-service:
    container_name: piperchat-db-monitoring-service
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=db-monitoring-service-username
      - MONGO_INITDB_ROOT_PASSWORD=db-monitoring-service-password
      - MONGO_INITDB_DATABASE=db-monitoring-service-database
    volumes:
      - ./.docker/monitoring-service:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongo --quiet $${host}/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    depends_on:
      db-monitoring-service:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: db-monitoring-service-username
      ME_CONFIG_MONGODB_ADMINPASSWORD: db-monitoring-service-password
      ME_CONFIG_MONGODB_SERVER: piperchat-db-monitoring-service
